---
title: "Capstone"
author: "Jack Freier"
date: "9/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE)
```

```{r message=FALSE}
# Libraries
library(dplyr)
library(lubridate)
library(stringr)
library(ggplot2)
library(tidyr)
library(astsa)
library(splines)

library(zoo)
library(vars)
```


```{r}
# Read the .csv files into R
Data_Coal = read.csv(file = 'MER_T06_01.csv', header = FALSE)
Data_NatGas = read.csv(file = 'MER_T04_01.csv', header = FALSE)


# Transform coal data into a data frame
DF_Coal = data.frame(Date = Data_Coal$V2,
                Value = Data_Coal$V3,
                Units = Data_Coal$V6,
                Description = Data_Coal$V5,
                MSN = Data_Coal$V1)

# Transform natural gas data into a data frame
DF_NatGas = data.frame(Date = Data_NatGas$V2,
                Value = Data_NatGas$V3,
                Units = Data_NatGas$V6,
                Description = Data_NatGas$V5,
                MSN = Data_NatGas$V1)


# Extract relevant rows and reindex
DF_Coal = DF_Coal[-1,]
rownames(DF_Coal) = NULL

DF_NatGas = DF_NatGas[-1,]
rownames(DF_NatGas) = NULL


# Turn entries into numeric values
DF_Coal$Date = as.numeric(as.character(DF_Coal$Date))
DF_Coal$Value = as.numeric(as.character(DF_Coal$Value))

DF_NatGas$Date = as.numeric(as.character(DF_NatGas$Date))
DF_NatGas$Value = as.numeric(as.character(DF_NatGas$Value))


# Separate 'Date' variable into 'Year' and 'Month'
DF_Coal = DF_Coal %>%
  separate(Date, c("Year", "Month"), sep = 4, remove = TRUE, convert = TRUE)

DF_NatGas = DF_NatGas %>%
  separate(Date, c("Year", "Month"), sep = 4, remove = TRUE, convert = TRUE)


# Create a continuous 'Time' variable
DF_Coal = DF_Coal %>%
  mutate(Time = Year + (Month - 1) / 12)

DF_NatGas = DF_NatGas %>%
  mutate(Time = Year + (Month - 1) / 12)


# Reorder columns
DF_Coal = DF_Coal[c(1, 2, 7, 3, 4, 5, 6)]

DF_NatGas = DF_NatGas[c(1, 2, 7, 3, 4, 5, 6)]


# Filter out annual totals, revelant variables, and incomplete cases
DF_Coal = DF_Coal %>%
  filter(Month %in% c(1:12)) %>%
  filter(Description == "Coal Consumption") %>%
  filter(complete.cases(.))

DF_NatGas = DF_NatGas %>%
  filter(Month %in% c(1:12)) %>%
  filter(Description == "Natural Gas Consumption") %>%
  filter(complete.cases(.))
```

```{r}
# Plot the time series coal data
DF_Coal %>%
  ggplot(aes(x = Time, y = Value)) +
  geom_point(size = 1) +
  geom_line() +
  labs(x = "Year", y = "Coal Consumption   (Thousand Short Tons)") +
  ggtitle("National Coal Consumption - 1973 to 2019") +
  scale_x_continuous(breaks = c(seq(1975, 2021, 5)), limits = c(1973, 2021)) +
  scale_y_continuous(breaks = c(seq(35000, 110000, 10000)), limits = c(35000, 110000)) +
  theme_minimal()

# Plot the time series natural gas data
DF_NatGas %>%
  ggplot(aes(x = Time, y = Value)) +
  geom_point(size = 1) +
  geom_line() +
  labs(x = "Year", y = "Natural Gas Consumption   (Billion Cubic Feet)") +
  ggtitle("National Natural Gas Consumption - 1973 to 2019") +
  scale_x_continuous(breaks = c(seq(1975, 2021, 5)), limits = c(1973, 2021)) +
  scale_y_continuous(breaks = c(seq(750, 3500, 500)), limits = c(750, 3500)) +
  theme_minimal()
```

```{r}
# Coal Trend - Spline Fit
splineTrendCoal = lm(Value ~ bs(Time, degree = 2, knots = c(2006, 2010),
                            Boundary.knots = c(1973, 2021.750)), data = DF_Coal)

DF_Coal = DF_Coal %>%
  mutate(Trend = predict(splineTrendCoal))

# Plot the coal series with trend fit
DF_Coal %>%
  ggplot(aes(x = Time, y = Value)) +
  geom_point() +
  scale_x_continuous(breaks = c(seq(1975, 2020, 5)), limits = c(1973, 2020)) +
  scale_y_continuous(breaks = c(seq(35000, 110000, 10000)), limits = c(35000, 110000)) +
  labs(x = "Year", y = "Coal Consumption   (Thousand Short Tons)") +
  ggtitle("National Coal Consumption - Spline Fit") +
  geom_line(aes(x = Time, y = Trend), color = "purple", size = 0.75) +
  theme_minimal()


# Natural Gas Trend - Spline Fit
splineTrendGas = lm(Value ~ bs(Time, degree = 2, knots = c(1980, 1985, 1995, 2000),
                            Boundary.knots = c(1973, 2021.750)), data = DF_NatGas)

DF_NatGas = DF_NatGas %>%
  mutate(Trend = predict(splineTrendGas))

# Plot the natural gas series with trend fit
DF_NatGas %>%
  ggplot(aes(x = Time, y = Value)) +
  geom_point() +
  scale_x_continuous(breaks = c(seq(1975, 2021, 5)), limits = c(1973, 2021)) +
  scale_y_continuous(breaks = c(seq(750, 3500, 500)), limits = c(750, 3500)) +
  labs(x = "Year", y = "Natural Gas Consumption   (Billion Cubic Feet)") +
  ggtitle("National Natural Gas Consumption - Spline Fit") +
  geom_line(aes(x = Time, y = Trend), color = "purple", size = 0.75) +
  theme_minimal()
```

```{r}
# De-Trended Coal - Spline Fit
DF_Coal = DF_Coal %>%
  mutate(Residuals = Value - Trend)

# Plot coal data after removing trend (by Month and Year)
DF_Coal %>%
  ggplot(aes(x = factor(Month), y = Residuals, color = factor(Year))) +
  geom_line(aes(group = factor(Year)), size = 0.75) +
  scale_y_continuous(breaks = c(seq(-25000, 25000, 5000)), limits = c(-25000, 25000)) +
  ggtitle("De-Trended Coal Observations") +
  labs(x = "Month", y = "Coal Residuals   (Thousand Short Tons)", color = "Year") +
  theme_minimal()


# De-Trended Gas - Spline Fit
DF_NatGas = DF_NatGas %>%
  mutate(Residuals = Value - Trend)

# Plot coal data after removing trend (by Month and Year)
DF_NatGas %>%
  ggplot(aes(x = factor(Month), y = Residuals, color = factor(Year))) +
  geom_line(aes(group = factor(Year)), size = 0.75) +
  scale_y_continuous(breaks = c(seq(-750, 1250, 250)), limits = c(-750, 1250)) +
  ggtitle("De-Trended Natural Gas Observations") +
  labs(x = "Month", y = "Natural Gas Residuals   (Billion Cubic Feet)", color = "Year") +
  theme_minimal()
```

```{r}
# Coal - Create a categorical variable splitting Year into two subgroups
DF_Coal$Before2008 = cut(DF_Coal$Year, c(1972, 2007, 2019), labels = c("YES", "NO"))

# Create a factored 'Month' variable for coal
DF_Coal = DF_Coal %>%
  mutate(Month = factor(Month))

# Create a model for coal seasonality
Coal_Season = lm(DF_Coal$Residuals ~ Month * Before2008, data = DF_Coal)

DF_Coal = DF_Coal %>%
  mutate(Season = predict(Coal_Season, newdata = data.frame(Month = DF_Coal$Month,
                                                       Before2008 = DF_Coal$Before2008))) %>%
  mutate(Residuals.SE = Residuals - Season)

# Coal residual series after removing trend and seasonality
DF_Coal %>%
  ggplot(aes(x = Time, y = Residuals.SE)) +
  geom_point(na.rm = TRUE) +
  geom_smooth(na.rm = TRUE, method = 'lm', formula = y ~ x)+
  scale_y_continuous(breaks = c(seq(-15000, 15000, 5000)), limits = c(-15000, 15000)) +
  ggtitle("Coal -- Residual Series After Removing Trend and Seasonality") +
  labs(x = "Year", y = "Errors   (Thousand Short Tons)") +
  theme_minimal()


# Create a factored 'Month' variable for natural gas
DF_NatGas = DF_NatGas %>%
  mutate(Month = factor(Month))

# Create a model for natural gas seasonality
Gas_Season = lm(DF_NatGas$Residuals ~ Month, data = DF_NatGas)

DF_NatGas = DF_NatGas %>%
  mutate(Season = predict(Gas_Season, newdata = data.frame(Month = DF_NatGas$Month))) %>%
  mutate(Residuals.SE = Residuals - Season)

# Natural gas residual series after removing trend and seasonality
DF_NatGas %>%
  ggplot(aes(x = Time, y = Residuals.SE)) +
  geom_point(na.rm = TRUE) +
  geom_smooth(na.rm = TRUE, method = 'lm', formula = y ~ x)+
  scale_y_continuous(breaks = c(seq(-500, 500, 100)), limits = c(-500, 500)) +
  ggtitle("Natural Gas -- Residual Series After Removing Trend and Seasonality") +
  labs(x = "Year", y = "Errors   (Billion Cubic Feet)") +
  theme_minimal()
```

```{r}
#################### VAR Model ####################

# Create a time series object
Coal = ts(DF_Coal$Residuals.SE, start = c(1973, 1), end = c(2019, 10), frequency = 12)
Natural_Gas = ts(DF_NatGas$Residuals.SE, start = c(1973, 1), end = c(2019, 10), frequency = 12)

# Plot the two time series
x = cbind(Coal, Natural_Gas)
plot.ts(x , main = "Coal and Natural Gas Residual Series - 1973 to 2019", xlab = "Year")

# Find optimal lag values
VARselect(x, type = "const")

# Input optimal lag and deterministic regressors
fitvar1 = VAR(x, p = 10, type = "both")

# ACF of the residual series
acf(residuals(fitvar1)[,1])
acf(residuals(fitvar1)[,2])

# Plot of orthogonal impulse responses
plot(irf(fitvar1, impulse = "Coal", ortho = TRUE))
plot(irf(fitvar1, impulse = "Natural_Gas", ortho = TRUE))

# Plot of the forecast error variance decoposition
plot(fevd(fitvar1, n.ahead = 24))

# Plot of predictions for the next two years
predictions <- predict(fitvar1, n.ahead = 24, ci = 0.95)
plot(predictions, xlim = c(450, 600), names = "Coal")
plot(predictions, xlim = c(450, 600), names = "Natural_Gas")
```

```{r}
trend.mod.coal = lm(Value ~ bs(Time, degree = 2, knots = c(2006, 2010), Boundary.knots = c(1973, 2021.750)) 
                    + Month * Before2008, data = DF_Coal)

trend.mod.natgas = lm(Value ~ bs(Time, degree = 2, knots = c(1980, 1985, 1995, 2000), Boundary.knots = c(1973, 2021.750)) 
                      + Month, data = DF_NatGas)

newdat = data.frame(Month = as.factor(c(10:12, 1:12, 1:9)), Time = 2019.333 + (1:24)/12, Before2008 = as.factor(rep("NO", 24)))

predict.mod.coal = predict(trend.mod.coal, newdat)
predict.mod.natgas = predict(trend.mod.natgas, newdat)

predict.mod.coal
predict.mod.natgas
```




```{r}
#################### SARIMA Model ####################

acf(DF_Coal$Residuals.SE, main = "Coal - Autocorrelation")

pacf(DF_Coal$Residuals.SE, main = "Coal - Partial Autocorrelation")

# AR(1) and Seasonal MA(1) model for estimation and removal of the trend / seasonality
mod.fit.EST = sarima(DF_Coal$Residuals.SE, p = 1, d = 0, q = 0, P = 0, D = 0, Q = 1, S = 12)
mod.fit.EST

# Consolidate models for both trend and seasonality
trend.mod = lm(Value ~ bs(Time, degree = 2, knots = c(2006, 2010), Boundary.knots = c(1973, 2021.750))
                + Month * Before2008, data = DF_Coal)

# Create a matrix of model coefficients - Remove intercept column
X = model.matrix(trend.mod)[,-1]

# Initialize new time values for forecasting
newdat = data.frame(Month = c(10:12, 1:12, 1:9), Time = 2019.333 + (1:24)/12, Before2008 = rep(0, 24))

# Create a new matrix of model coefficients - Remove intercept column
new.X = model.matrix(~ bs(Time, degree = 2, knots = c(2006, 2010), Boundary.knots = c(1973, 2021.750))
                + factor(Month) * Before2008, data = newdat)[,-1]

# Forecast using the SARIMA model
sarima.for(DF_Coal$Value, n.ahead = 24, p = 1, d = 0, q = 0, P = 0, D = 0, Q = 1, S = 12, xreg = X, newxreg = new.X)
```
